
spring.application.name=snapquest
spring.datasource.url=jdbc:postgresql://localhost:5432/snapquest
spring.datasource.username=macbookpro
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
app.jwt.secret=snapquest-super-secret-key-change-this-in-production-min-256-bits
app.jwt.expiration-ms=86400000
gemini.api.key=AIzaSyCaGpatCm3D1w_OqBci6Xaw7q8rVAQW9fI